apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo-app
  namespace: demo-app
  labels:
    app: eks-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-demo-app
  template:
    metadata:
      labels:
        app: eks-demo-app
    spec:
      containers:
      - name: eks-demo-app
        image: 423535494352.dkr.ecr.us-east-1.amazonaws.com/eks-demo-app
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_VERSION
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5